version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123321
      POSTGRES_USER: harn
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U harn -h localhost -p 5432 -d test"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
